version: "3.9"

services:

  db:
    image: mysql:8
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'rootroot'
      MYSQL_DATABASE: 'mediscreen'
    ports:
      - '3307:3306'
    networks:
      - mediscreen-network
    volumes:
      - mediscreendb:/var/lib/mysql
      
  mongo:
     image: mongo:latest
     container_name: mongoDB
     restart: always
     ports:
       - '33017:33017'
     networks:
       - mediscreen-network
     volumes:
       - mediscreendb:/var/lib/mongo
      
  patient:
    depends_on:
     - db
    image: guardians59/ms-patient-image
    container_name: ms-patient
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/mediscreen?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootroot
    ports:
      - 8081:8081
    restart: always
    networks:
      - mediscreen-network
      
  note:
    depends_on:
     - mongo
    image: guardians59/ms-notes-image
    container_name: ms-note
    ports:
     - 8082:8082
    restart: always
    networks:
     - mediscreen-network
     
  report:
    depends_on:
     - mongo
    image: guardians59/ms-report-image
    container_name: ms-report
    ports:
     - 8083:8083
    restart: always
    networks:
     - mediscreen-network
      
networks:
  mediscreen-network:
    driver: bridge
    
volumes:
  mediscreendb:
      